Licenta/Controllers/LoginController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Security.Cryptography;
using System.Text;
using System.Web;
using System.Web.Mvc;
using Licenta.Models;
using Microsoft.Rest.ClientRuntime.Azure.Authentication.Utilities;

namespace Licenta.Controllers
{
    public class LoginController : Controller

    {
        
        // GET: Login
        public ActionResult Index()
        {
            ViewBag.Message = "Autentificare";

            return View();
        }

        public ActionResult Login(Login login)
        {
            if (!ModelState.IsValid)
            {
                return View("Index");
            }
            else
            {

            
            using(DbLicentaEntities db=new DbLicentaEntities())
            {
                //pt parola
                SHA256 sha256 = SHA256Managed.Create();
                UTF8Encoding objUtf8 = new UTF8Encoding();
                var hashValue = sha256.ComputeHash(objUtf8.GetBytes(login.Password));
                var hashedPassword = Encoding.Default.GetString(hashValue);


                var userDetails = db.User.Where(x => x.EmailAddress == login.EmailAddress
                    && x.Password==hashedPassword).FirstOrDefault();

                if (userDetails == null)
                {
                    
                    login.LoginErrorMessage = "Adresa de mail sau parola sunt gresite!";
                    return View("Index",login);
                }
                else
                {
                //    AppSession.IsUserLogged = true;
                //    AppSession.LoggedUser = userDetails;
                    AppSession.Login(userDetails);
                    return RedirectToAction("Index", "Home");
                }
            }
            }
        }

        public ActionResult LogOut()
        {
        
            AppSession.LogOut();
            return RedirectToAction("Index", "Home");
        }
    }
}

Licenta/Controllers/ProgramariController.cs
using System.Collections.Generic;
using Licenta.Models;
using System.Linq;
using System.Web.Mvc;

namespace Licenta.Controllers
{
    public class ProgramariController : Controller
    {
        //private DbLicentaEntities context;
        private ProgramareCasatorieAdmin casatorieAdminModel;
        private AudientaAdmin audientaAdminModel;

        public ProgramariController()
        {
            audientaAdminModel = new AudientaAdmin();
            casatorieAdminModel = new ProgramareCasatorieAdmin();
           // context = new DbLicentaEntities();
        }
        // GET: Programari
        public ActionResult Index()
        {
            return View("Index");
        }

        public ActionResult AddPVStareCivila(string message)
        {
            var programareCasatorie = new ProgramareCasatorie();
            programareCasatorie.BookedMarriages = new List<KeyValuePair<string, string>>();
            using (var context = new DbLicentaEntities())
            {
                var x = context.Marriage.ToList();
                foreach (var item in x)
                {
                    programareCasatorie.BookedMarriages.Add(new KeyValuePair<string, string>(item.Date,item.Hour));
                }
            }

            if (!string.IsNullOrEmpty(message))
            {
                programareCasatorie.SuccessMessage = message;
            }

            return View("_CasatorieUser", programareCasatorie);
        }
    
        public ActionResult SaveMarriage(ProgramareCasatorie programare)
        {
            if (!ModelState.IsValid)
            {
                return View("_CasatorieUser", programare);
            }
            else
            {
                using (var context = new DbLicentaEntities())
                {
                    var appSession = AppSession.Instance();
                    context.Marriage.Add(new Marriage
                    {
                        Date = programare.Date,
                        Hour = programare.Hour,
                        HusbandName = programare.HusbandName,
                        HusbandCNP = programare.HusbandCNP,
                        WifeName = programare.WifeName,
                        WifeCNP = programare.WifeCNP,
                        EmailAdress = programare.EmailAdress,
                        PhoneNumber = programare.PhoneNumber,
                        UserId = appSession.LoggedUser.Id

                    });
                    context.SaveChanges();
                }
                //return View("_CasatorieUser", new ProgramareCasatorie {SuccessMessage = "Programare trimisa"});
                ModelState.Clear();
                return AddPVStareCivila("Programare trimisa");
            }
            
        }
        //admin use
        public ActionResult ProgramareCasatorieTable()
        {
            using (var context = new DbLicentaEntities())
            {
                casatorieAdminModel.marriages = context.Marriage.ToList();
            }
            return PartialView("_CasatorieAdminTable",casatorieAdminModel.marriages);
        }



        //pt audienta
        public ActionResult SaveAudienta(Audienta audienta)
        {
            if (!ModelState.IsValid)
            {
                return View("_AudientaUser",audienta);
            }
            else
            {
                using (var context = new DbLicentaEntities())
                {
                    var appSession = AppSession.Instance();
                    context.Audience.Add(new Audience
                    {
                        Nume = audienta.Nume,
                        Telefon = audienta.Telefon,
                        SolicitareLa = audienta.SolicitareLa,
                        Motiv = audienta.Motiv,
                        UserId = appSession.LoggedUser.Id

                    });

                    context.SaveChanges();
                }

                ModelState.Clear();
                return AddPVAudientaUser("Audienta inregistrata");
            }
            
        }
        public ActionResult SaveMentiuni(int audienceId, string mentiune)
        {
            using (var context = new DbLicentaEntities())
            {
                var audienceToEdit= context.Audience.Where(x => x.IdAudienta == audienceId).FirstOrDefault();
                audienceToEdit.Mentiuni = mentiune;
                context.SaveChanges();
            }
            return Index();
        }

        public ActionResult AddPVAudientaUser(string message)
        {
            Audienta audienta = new Audienta();

            if (!string.IsNullOrEmpty(message))
            {
                audienta.SuccesMesaj = message;
            }

            return View("_AudientaUser",audienta);
        }


        //admin audienta
        public ActionResult AudientaTable()
        {
            using (var context = new DbLicentaEntities())
            {
                audientaAdminModel.audiences = context.Audience.ToList();
            }
            return PartialView("_AudientaAdminTable", audientaAdminModel.audiences);
        }


        public ActionResult DeleteAudience(int audienceId)
        {
            using (var context = new DbLicentaEntities())
            {
                var audienceToRemove = context.Audience.Where(x => x.IdAudienta == audienceId).FirstOrDefault();
                context.Audience.Remove(audienceToRemove);
                context.SaveChanges();
                audientaAdminModel.audiences = context.Audience.ToList();
            }

            return Index();
        }

      

        //admin use
        public ActionResult DeleteMarriage(int marriageId)
        {
            using (var context = new DbLicentaEntities())
            {
                var marriageToRemove = context.Marriage.Where(x => x.Id == marriageId).FirstOrDefault();
                context.Marriage.Remove(marriageToRemove);
                context.SaveChanges();
                casatorieAdminModel.marriages = context.Marriage.ToList();
            }

            return Index();
        }

        //for documents selection
        public ActionResult getDocuments()
        {
            return PartialView("_Documents");
        }
        public ActionResult getPageLinks()
        {
            return PartialView("_PageLinks");
        }
    }




}

Licenta/Controllers/SesizareController.cs
using System.Collections.Generic;
using Licenta.Models;
using System.Linq;
using System.Security;
using System.Web.Mvc;

namespace Licenta.Controllers
{
    public class SesizareController : Controller
    {
        private SesizareAdmin sesizareAdminModel;
        private static string resultMessage;
        public SesizareController()
        {
            sesizareAdminModel = new SesizareAdmin();
        }
        // GET: Sesizare
        public ActionResult Index()
        {
            resultMessage = string.Empty;
            return View();
        }
        //for User use
        public ActionResult SesizareUser(Sesizare sesizare)
        {
            if (!ModelState.IsValid)
            {
                return View("_SesizareUser", sesizare);
            }
            else
            {
                var appSession = AppSession.Instance();
                if (appSession.IsUserLogged)
                {
                    using (var context = new DbLicentaEntities())
                    {
                        context.Report.Add(new Report
                        {
                            TitlulSesizarii = sesizare.TitluSesizare,
                            Adresa = sesizare.Adresa,
                            Descriere = sesizare.Descriere,
                            EsteUrgenta = sesizare.esteUrgenta,
                            UserId = appSession.LoggedUser.Id

                        });
                        context.SaveChanges();

                    }

                }
                sesizare.Message = "Sesizare dumnevoastra este trimisa!";
                ModelState.Clear();
                return View("Index", sesizare);

            }

        }

        //for Admin use

        public ActionResult SesizareAdminTable()
        {
            using (var context = new DbLicentaEntities())
            {
                sesizareAdminModel.Reports = context.Report.ToList();
            }
            return PartialView("_SesizareAdminTable", sesizareAdminModel.Reports);
        }

        public ActionResult SesizareResult()
        {
            return PartialView("_SesizareResult", resultMessage);
        }
        public ActionResult SesizareAdmin()
        {
            return PartialView("_SesizareAdmin", sesizareAdminModel);
        }

        public ActionResult ResolveReports(List<Report> reports)
        {
            var reps = reports.Select(x => x.Id).ToList();

            using (var context = new DbLicentaEntities())
            {
                var dbReports = context.Report
                    .Where(x=>reps.Contains(x.Id)).ToList();

                foreach (var report in dbReports)
                {
                    report.IsResolved = reports.Where(x => x.Id == report.Id).Select(x => x.IsResolved).First();
                }

                sesizareAdminModel.Reports = context.Report.ToList();
                resultMessage = "Sesizare rezolvata!";

                context.SaveChanges();
            }
            return View("Index");
        }
        

        public ActionResult loaddata()
        {
            using (DbLicentaEntities context = new DbLicentaEntities())
            {
                var data = context.Report.ToList();
                return Json(new { data = data }, JsonRequestBehavior.AllowGet);
            }
        }
    }
}

Licenta/Views/Shared/_Layout.cshtml
@using Licenta.Models
<!DOCTYPE html>
<html>
<head>

    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
    @Scripts.Render("~/bundles/lib")
    @Scripts.Render("~/bundles/jqueryui")


</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header" >
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Primăria Bogdănești", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav" style="font-size:17px;" >
                    <li>@Html.ActionLink("Acasă", "Index", "Home")</li>
                    <li>@Html.ActionLink("Programări/Documente", "Index", "Programari")</li>
                    <li>@Html.ActionLink("Depunere sesizări", "Index", "Sesizare")</li>
                    @if (!AppSession.Instance().IsUserLogged)
                    {
                        <li>@Html.ActionLink("Autentificare", "Index", "Login")</li>
                    }
                    else
                    {
                        <li>
                            <div class="dropdown">
                                <button class="btn dropdown-toggle" type="button" data-toggle="dropdown">
                                    Buna ziua @AppSession.Instance().LoggedUser.EmailAddress
                                    <span class="caret"></span>
                                </button>
                                <ul class="dropdown-menu">
                                    @if (!AppSession.Instance().LoggedUser.IsAdmin)
                                    {
                                        <li>@Html.ActionLink("Activitatile mele", "Index", "UserProfile")</li>
                                    }
                                    else
                                    {
                                        <li>@Html.ActionLink("Statistici", "GetStatistics", "UserProfile")</li>
                                    }


                                    <li><a href="@Url.Action("LogOut","Login")">Logout</a></li>

                                </ul>
                            </div>
                        </li>
                    }


                </ul>
            </div>
        </div>
    </div>


    <div class="container body-content">
        @RenderBody()
    </div>


    <footer id="footer">
        <hr />

        <div class="row" id="black" style="padding:20px 20px 20px 20px">
            <div class="col-lg-6">
                <p id="red">&copy; @DateTime.Now.Year - Primăria comunei Bogdănești, Suceava</p>
                <p>Telefon: 0756830839</p>
                <p>Email: bogdanestiSV@email.com</p>
                <p>Program: L-V / 8:00-16:00</p>
            </div>
            <div class="col-lg-6" style="text-align:right">
                <p id="red">Ia contact cu cine ai nevoie:</p>
                <p>Dispensar: 0756837464 / dispensarBog@gmail.com</p>
                <p>Stomatolog: 0753637449</p>
                <p>Biserica "Adormirea Maicii Domnului": 0788888888(Preot)</p>
                <p>Biserica pe stil vechi: 0743564655(Preot)</p>
                <p>Pompe funebre: 0787374544</p>
            </div>

        </div>

    </footer>
</body>




</html>

<style>

    #footer {
        padding-left: 20px;
        padding-right: 20px;
        padding-top: 50px;
        padding-bottom: 20px;
        color: black;
        font-size: 14px;
    }
</style>



@RenderSection("Scripts", required: false)