Licenta/Models/AudientaAdmin.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace Licenta.Models
{
    public class AudientaAdmin
    {
        public List<Audience> audiences;
    }
}

Licenta/Controllers/DocumenteController.cs
using Licenta.Models;
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Licenta.Controllers
{
    public class DocumenteController : Controller
    {
        // GET: Documente
        //public ActionResult Index()
        //{
        //    //Fetch all files in the Folder (Directory).
        //    string[] filePaths = Directory.GetFiles(Server.MapPath(@"C:\Users\Ioana\Desktop\New folder\Licenta\Licenta\Licenta\Documents\"));

        //    //Copy File names to Model collection.
        //    List <FileModel> files = new List<FileModel>();
        //    foreach (string filePath in filePaths)
        //    {
        //        files.Add(new FileModel { FileName = Path.GetFileName(filePath) });
        //    }

        //    return View(files);
        //}
        //public FileResult DownloadFile(string fileName)
        //{
        //    //Build the File Path.
        //    string path = Server.MapPath(@"C:\Users\Ioana\Desktop\New folder\Licenta\Licenta\Licenta\Documents\") + fileName;

        //    //Read the File data into Byte Array.
        //    byte[] bytes = System.IO.File.ReadAllBytes(path);

        //    //Send the File to Download.
        //    return File(bytes, "application/octet-stream", fileName);
        //}

        public ActionResult InregistrareNasteri()
        {
            return View("_InregistrareNasteri");
        }
        public ActionResult InregistrareCasatorie()
        {
            return View("_Casatorie");
        }
        public ActionResult InregistrareDeces()
        {
            return View("_Deces");
        }
        public ActionResult EliberareCertificateStareCivila()
        {
            return View("_EliberareCertificate");
        }
        public ActionResult Divort()
        {
            return View("_Divort");
        }
        public ActionResult LivretulFamiliei()
        {
            return View("_LivretulFamiliei");
        }
    }
}

Licenta/Controllers/LoginController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Security.Cryptography;
using System.Text;
using System.Web;
using System.Web.Mvc;
using Licenta.Models;
using Microsoft.Rest.ClientRuntime.Azure.Authentication.Utilities;

namespace Licenta.Controllers
{
    public class LoginController : Controller

    {
        
        // GET: Login
        public ActionResult Index()
        {
            ViewBag.Message = "Autentificare";

            return View();
        }

        public ActionResult Login(Login login)
        {
            if (!ModelState.IsValid)
            {
                return View("Index");
            }
            else
            {

            
            using(DbLicentaEntities db=new DbLicentaEntities())
            {
                //pt parola
                SHA256 sha256 = SHA256Managed.Create();
                UTF8Encoding objUtf8 = new UTF8Encoding();
                var hashValue = sha256.ComputeHash(objUtf8.GetBytes(login.Password));
                var hashedPassword = Encoding.Default.GetString(hashValue);


                var userDetails = db.User.Where(x => x.EmailAddress == login.EmailAddress
                    && x.Password==hashedPassword).FirstOrDefault();

                if (userDetails == null)
                {
                    
                    login.LoginErrorMessage = "Adresa de mail sau parola sunt gresite!";
                    return View("Index",login);
                }
                else
                {
                //    AppSession.IsUserLogged = true;
                //    AppSession.LoggedUser = userDetails;
                    AppSession.Login(userDetails);
                    return RedirectToAction("Index", "Home");
                }
            }
            }
        }

        public ActionResult LogOut()
        {
        
            AppSession.LogOut();
            return RedirectToAction("Index", "Home");
        }
    }
}

Licenta/Controllers/ProgramariController.cs
using System.Collections.Generic;
using Licenta.Models;
using System.Linq;
using System.Web.Mvc;

namespace Licenta.Controllers
{
    public class ProgramariController : Controller
    {
        //private DbLicentaEntities context;
        private ProgramareCasatorieAdmin casatorieAdminModel;
        private AudientaAdmin audientaAdminModel;

        public ProgramariController()
        {
            audientaAdminModel = new AudientaAdmin();
            casatorieAdminModel = new ProgramareCasatorieAdmin();
           // context = new DbLicentaEntities();
        }
        // GET: Programari
        public ActionResult Index()
        {
            return View("Index");
        }

        public ActionResult AddPVStareCivila(string message)
        {
            var programareCasatorie = new ProgramareCasatorie();
            programareCasatorie.BookedMarriages = new List<KeyValuePair<string, string>>();
            using (var context = new DbLicentaEntities())
            {
                var x = context.Marriage.ToList();
                foreach (var item in x)
                {
                    programareCasatorie.BookedMarriages.Add(new KeyValuePair<string, string>(item.Date,item.Hour));
                }
            }

            if (!string.IsNullOrEmpty(message))
            {
                programareCasatorie.SuccessMessage = message;
            }

            return View("_CasatorieUser", programareCasatorie);
        }
    
        public ActionResult SaveMarriage(ProgramareCasatorie programare)
        {
            if (!ModelState.IsValid)
            {
                return View("_CasatorieUser", programare);
            }
            else
            {
                using (var context = new DbLicentaEntities())
                {
                    var appSession = AppSession.Instance();
                    context.Marriage.Add(new Marriage
                    {
                        Date = programare.Date,
                        Hour = programare.Hour,
                        HusbandName = programare.HusbandName,
                        HusbandCNP = programare.HusbandCNP,
                        WifeName = programare.WifeName,
                        WifeCNP = programare.WifeCNP,
                        EmailAdress = programare.EmailAdress,
                        PhoneNumber = programare.PhoneNumber,
                        UserId = appSession.LoggedUser.Id

                    });
                    context.SaveChanges();
                }
                //return View("_CasatorieUser", new ProgramareCasatorie {SuccessMessage = "Programare trimisa"});
                ModelState.Clear();
                return AddPVStareCivila("Programare trimisa");
            }
            
        }
        //admin use
        public ActionResult ProgramareCasatorieTable()
        {
            using (var context = new DbLicentaEntities())
            {
                casatorieAdminModel.marriages = context.Marriage.ToList();
            }
            return PartialView("_CasatorieAdminTable",casatorieAdminModel.marriages);
        }



        //pt audienta
        public ActionResult SaveAudienta(Audienta audienta)
        {
            if (!ModelState.IsValid)
            {
                return View("_AudientaUser",audienta);
            }
            else
            {
                using (var context = new DbLicentaEntities())
                {
                    var appSession = AppSession.Instance();
                    context.Audience.Add(new Audience
                    {
                        Nume = audienta.Nume,
                        Telefon = audienta.Telefon,
                        SolicitareLa = audienta.SolicitareLa,
                        Motiv = audienta.Motiv,
                        UserId = appSession.LoggedUser.Id

                    });

                    context.SaveChanges();
                }

                ModelState.Clear();
                return AddPVAudientaUser("Audienta inregistrata");
            }
            
        }
        public ActionResult SaveMentiuni(int audienceId, string mentiune)
        {
            using (var context = new DbLicentaEntities())
            {
                var audienceToEdit= context.Audience.Where(x => x.IdAudienta == audienceId).FirstOrDefault();
                audienceToEdit.Mentiuni = mentiune;
                context.SaveChanges();
            }
            return Index();
        }

        public ActionResult AddPVAudientaUser(string message)
        {
            Audienta audienta = new Audienta();

            if (!string.IsNullOrEmpty(message))
            {
                audienta.SuccesMesaj = message;
            }

            return View("_AudientaUser",audienta);
        }


        //admin audienta
        public ActionResult AudientaTable()
        {
            using (var context = new DbLicentaEntities())
            {
                audientaAdminModel.audiences = context.Audience.ToList();
            }
            return PartialView("_AudientaAdminTable", audientaAdminModel.audiences);
        }


        public ActionResult DeleteAudience(int audienceId)
        {
            using (var context = new DbLicentaEntities())
            {
                var audienceToRemove = context.Audience.Where(x => x.IdAudienta == audienceId).FirstOrDefault();
                context.Audience.Remove(audienceToRemove);
                context.SaveChanges();
                audientaAdminModel.audiences = context.Audience.ToList();
            }

            return Index();
        }

      

        //admin use
        public ActionResult DeleteMarriage(int marriageId)
        {
            using (var context = new DbLicentaEntities())
            {
                var marriageToRemove = context.Marriage.Where(x => x.Id == marriageId).FirstOrDefault();
                context.Marriage.Remove(marriageToRemove);
                context.SaveChanges();
                casatorieAdminModel.marriages = context.Marriage.ToList();
            }

            return Index();
        }

        //for documents selection
        public ActionResult getDocuments()
        {
            return PartialView("_Documents");
        }
        public ActionResult getPageLinks()
        {
            return PartialView("_PageLinks");
        }
    }




}

Licenta/Views/Programari/Index.cshtml
@using Licenta.Models
@{
    ViewBag.Title = "Programări";
}


<div class="header">
    <h2>Primăria comunei Bogdănești</h2>
    <hr id="line">
</div>

@if (AppSession.Instance().LoggedUser == null)
{
    <div class="row">
        <div class="col-sm-3 civil">
            <div class="chenar">
                <p id="red" style="font-size:22px;">Stare civilă</p>
                @Html.Action("getPageLinks")
            </div>
        </div>
        <div class="col-sm-6">
            <h2>Pentru a putea face o programre trebuie sa fiți autentificat.</h2>
            <div style="text-align:center">
                <button class="btn">@Html.ActionLink("Autentificare", "Index", "Login")</button>
            </div>
        </div>
        <div class="col-sm-3 ">
            <div class="chenar2">
                <div>
                    @Html.Action("getDocuments")
                </div>

            </div>
        </div>
    </div>
}
else if (AppSession.Instance().LoggedUser.IsAdmin)
{
    <div>
        <h1>Tabel programări casătorie</h1>
        @Html.Action("ProgramareCasatorieTable")
    </div>
    <br />

    <div>
        <h1>Tabel audiențe înregistrate</h1>
        @Html.Action("AudientaTable")
    </div>


}
else
{
    <div class="row">
        <div class="col-sm-3 civil">
            <div class="chenar">
                <p id="red" style="font-size:22px;"> Stare civila </p>
                @Html.Action("getPageLinks")
            </div>
        </div>
        <div class="col-sm-6">
            <div id="user">
                <h1>Bun venit!</h1>
                <p>Administrația locală îți mulțmește că ai ales acestă cale ușoară de a-ți rezolva problemele.</p>
                <p>Împreună contribuim la dezvoltarea comunității noastre.</p>
                <br />

                <h1>Programare căsătorie</h1>
                <br />
                <img src="~/image/wedd.jpg" />
                <br />
                <br />
                <p>Pentru a rezerva ziua și ora la care va avea loc fericitul eveniment, vă rugăm să accesați următorul link: </p>
                <br />
                <div style="text-align:center">
                    <button class="btn" style="width:300px;">@Html.ActionLink("Programare căsătorie", "AddPVStareCivila", "Programari") </button>
                </div>

                <br />
                <br />
                <hr id="line" />
                <br />


                <h1>Înscriere în audiență</h1>
                <br />
                <img src="~/image/audienta.jpg" />
                <br />
                <br />
                <p>După confirmarea înscrierii, veți fi contactat telefonic în vederea soluționării solicitării.</p>
                <br />
                <div style="text-align:center">
                    <button class="btn" style="width:300px;">@Html.ActionLink("Înregistrare audiență", "AddPVAudientaUser", "Programari")</button>
                </div>
            </div>
        </div>

        <div class="col-sm-3 ">
            <div class="chenar2">
                <div>
                    @Html.Action("getDocuments")
                </div>

            </div>
        </div>
    </div>

}
<br />
<br />
<br />


<style>





    .col-sm-6.view {
        font-family: Georgia, 'Times New Roman', Times, serif;
        background-color: rgba(240, 242, 245,0.5);
        padding: 5px 5px 5px 5px;
        font-size: 20px;
        color: black;
        text-align: justify;
    }

    h1 {
        text-align: center;
    }

    img {
        width: 100%;
    }
</style>

<link href="//cdn.datatables.net/1.10.25/css/jquery.dataTables.min.css">
@section Scripts {
    <script src="//cdn.datatables.net/1.10.25/js/jquery.dataTables.min.js"></script>
    <script type="text/javascript">
        $(document).ready(function () {
            $('#marriageTable').DataTable();
        });

        jQuery(document).ready(function () {
            $('input[type="text"]').val('');
            show_alert();
        });

        function show_alert() {
            debugger;
            jQuery('[show_alert]').click(function (e) {
                if (!confirm(jQuery(this).attr("show_alert"))) {
                    e.preventDefault();
                } else {
                    window.location.href = eval(jQuery(this).attr("nextUrlAction"));
                }
            });
        }

    </script>
}

Licenta/Views/Programari/_AudientaAdminTable.cshtml
@model List<Audience>
<table id="marriageTable" class="table table-bordered table-hover">

    <thead>
        <tr>
            <th>Id audienta</th>
            <th>Id user</th>
            <th>Nume si prenume</th>
            <th>Telefon</th>
            <th>Audienta solicitata la</th>
            <th>Motivul</th>
            <th>Anulata</th>
            <th>Mentiuni</th>
        </tr>
    </thead>
    <tbody>
        @for (int i = 0; i < Model.Count; i++)
        {
            <tr>
                <td>
                    @Html.DisplayFor(x => x[i].IdAudienta)
                    @Html.HiddenFor(x => x[i].IdAudienta)
                </td>
                <td>
                    @Html.DisplayFor(x => x[i].UserId)
                    @Html.HiddenFor(x => x[i].UserId)
                </td>
                <td>
                    @Html.DisplayFor(x => x[i].Nume)
                    @Html.HiddenFor(x => x[i].Nume)
                </td>
                <td>
                    @Html.DisplayFor(x => x[i].Telefon)
                    @Html.HiddenFor(x => x[i].Telefon)
                </td>
                <td>
                    @Html.DisplayFor(x => x[i].SolicitareLa)
                    @Html.HiddenFor(x => x[i].SolicitareLa)
                </td>
                <td>
                    @Html.DisplayFor(x => x[i].Motiv)
                    @Html.HiddenFor(x => x[i].Motiv)
                </td>

                <td>
                    @Html.CheckBoxFor(x => x[i].isCanceled, new { @disabled = "disabled" })
                    @Html.HiddenFor(x => x[i].isCanceled)
                </td>
                <td>
                    @Html.DisplayFor(x => x[i].Mentiuni)
                    @*@Html.HiddenFor(x => x[i].Mentiuni)*@
                </td>
                <td>
                    <div class="form-group">
                        @Html.TextBoxFor(x => x[i].Mentiuni, new { @class = "form-control", id = "mentiunea[" + @Model[i].IdAudienta + "]" })
                    </div>
                </td>

                <td>
                    <input type="submit"  value="Salveaza mentiuni" onclick="location.href='@Url.Action("SaveMentiuni", "Programari")'+'?audienceId='+@Model[i].IdAudienta+'&mentiune=' + document.getElementById('mentiunea['+@Model[i].IdAudienta+']').value" />

                </td>
                <td>
                    <input type="submit" class="show_alert" value="Sterge" show_alert="Esti sigur?" nextUrlAction="'@Url.Action("DeleteAudience", "Programari",
                                                                                                             new { audienceId = @Model[i].IdAudienta})'" />
                </td>
            </tr>
        }
    </tbody>
</table>

Licenta/Views/Programari/_AudientaUser.cshtml
@using Licenta.Models
@model Licenta.Models.Audienta
<div id="user">
    <h1 id="programariTitlu">Inscriere in audienta</h1>
    <p id="black">După trimiterea cererii de inscriere in audienta, veti fi contactat in maxim 3 ore de un reprezentant in vederea solutionarii sau reprogramarii.</p>

    <din style="color:royalblue">
        <label class="field-validation-error"> @Html.DisplayFor(m => m.SuccesMesaj)</label>
    </din>
    @using (Html.BeginForm("SaveAudienta", "Programari"))
    {
        @Html.ValidationSummary(true, "Campurile de mai jos sunt obligatorii!")
        <div class="form-group">
            @Html.LabelFor(m => m.Nume, "Nume si prenume")
            @Html.TextBoxFor(m => m.Nume, new { @class = "form-control" })
            @Html.ValidationMessageFor(m => m.Nume)
        </div>

        <div class="form-group">
            @Html.LabelFor(m => m.Telefon, "Telefon")
            @Html.TextBoxFor(m => m.Telefon, new { @class = "form-control" })
            @Html.ValidationMessageFor(m => m.Telefon)
        </div>
        <div class="form-group">
            @Html.LabelFor(m => m.SolicitareLa, "Audienta solicitata la: ")
            @Html.DropDownListFor(m => m.SolicitareLa, new SelectList(Solicitare.Solicitari), "Selectati aici", new { @class = "form-control" })
            @Html.ValidationMessageFor(m => m.SolicitareLa)
        </div>
        <div class="form-group">
            @Html.LabelFor(m => m.Motiv, "Motivul audientei: ")
            @Html.TextBoxFor(m => m.Motiv, new { @class = "form-control" })
            @Html.ValidationMessageFor(m => m.Motiv)
        </div>

        <div style="text-align:center">
            <button class="btn" style="width:400px;">Trimite</button>
        </div>
    }
</div>

Licenta/Views/Programari/_CasatorieAdminTable.cshtml
@model List<Marriage>

@using (Html.BeginForm("ViewCasatorii", "Programari"))
{


    <table id="marriageTable" class="table table-bordered table-hover">
        <thead>
            <tr>

                <th>Id programare</th>
                <th>Id user</th>

                <th>Data</th>
                <th>Ora</th>
                <th>Sot</th>
                <th>CNP sot</th>
                <th>Sotie</th>
                <th>CNP sotie</th>
              
                <th>Email</th>
                <th>Telefon</th>
                <th>Anulata</th>
            </tr>
        </thead>
        <tbody>
            @for (int i = 0; i < Model.Count; i++)
            {
                <tr>
                    <td >
                        @Html.DisplayFor(x => x[i].Id)
                        @Html.HiddenFor(x => x[i].Id)
                    </td>
                    <td>
                        @Html.DisplayFor(x => x[i].UserId)
                        @Html.HiddenFor(x => x[i].UserId)
                    </td>
                    <td>
                        @Html.DisplayFor(x => x[i].Date)
                        @Html.HiddenFor(x => x[i].Date)
                    </td>
                    <td>
                        @Html.DisplayFor(x => x[i].Hour)
                        @Html.HiddenFor(x => x[i].Hour)
                    </td>
                    <td>
                        @Html.DisplayFor(x => x[i].HusbandName)
                        @Html.HiddenFor(x => x[i].HusbandName)
                    </td>

                    <td>
                        @Html.DisplayFor(x => x[i].HusbandCNP)
                        @Html.HiddenFor(x => x[i].HusbandCNP)
                    </td>
                    <td>
                        @Html.DisplayFor(x => x[i].WifeName)
                        @Html.HiddenFor(x => x[i].WifeName)
                    </td>
                    <td>
                        @Html.DisplayFor(x => x[i].WifeCNP)
                        @Html.HiddenFor(x => x[i].WifeCNP)
                    </td>
                    <td>
                        @Html.DisplayFor(x => x[i].EmailAdress)
                        @Html.HiddenFor(x => x[i].EmailAdress)
                    </td>
                    <td>
                        @Html.DisplayFor(x => x[i].PhoneNumber)
                        @Html.HiddenFor(x => x[i].PhoneNumber)
                    </td>
                    <td>
                        @Html.CheckBoxFor(x => x[i].IsCanceled, new { @disabled = "disabled" })
                        @Html.HiddenFor(x => x[i].IsCanceled)
                    </td>
                    <td>
                        <input type="submit" class="show_alert" value="Sterge" show_alert="Esti sigur?" nextUrlAction="'@Url.Action("DeleteMarriage", "Programari",
        new { marriageId = @Model[i].Id })'" />
                      
                    </td>
                </tr>
            }
        </tbody>
    </table>
}

@section Scripts {
    <script type="text/javascript">
        
        function show_alert() {
            debugger;
            jQuery('[show_alert]').click(function (e) {
                if (!confirm(jQuery(this).attr("show_alert"))) {
                    e.preventDefault();
                } else {
                    window.location.href = eval(jQuery(this).attr("nextUrlAction"));
                }
            });
        }
    </script>

}

Licenta/Views/Programari/_CasatorieUser.cshtml
@using Licenta.Models
@model Licenta.Models.ProgramareCasatorie
<div id="user">
    <h1 id="programariTitlu">Stare Civila</h1>
    @using (Html.BeginForm("SaveMarriage", "Programari"))
    {
        <din style="text-align:center;color:royalblue">
            <label class="field-validation-error"> @Html.DisplayFor(m => m.SuccessMessage)</label>
        </din>
        @Html.ValidationSummary(true, "Campurile de mai jos sunt obligatorii!")
        <div class="form-group">
            @Html.LabelFor(m => m.Date, "Data")
            @Html.TextBoxFor(model => model.Date, "{0:dd/MM/yyyy}", new { @class = "form-control", placeholder = "Enter Drop-off date here...", @readonly = "readonly", @style = "background-color: #FFFFFF" })
            @Html.ValidationMessageFor(m => m.Date)
        </div>
        <div class="form-group">
            @Html.LabelFor(m => m.Hour, "Ora")
            @Html.DropDownListFor(m => m.Hour,
                new SelectList(Tools.Hours),
                "SelectatiOra",
                new { @class = "form-control" }
                )
            @Html.ValidationMessageFor(m => m.Hour)
        </div>
        <div class="form-group">
            @Html.LabelFor(m => m.HusbandName, "Nume sot")
            @Html.TextBoxFor(m => m.HusbandName, new { @class = "form-control" })
            @Html.ValidationMessageFor(m => m.HusbandName)
        </div>
        <div class="form-group">
            @Html.LabelFor(m => m.HusbandCNP, "CNP sot")
            @Html.TextBoxFor(m => m.HusbandCNP, new { @class = "form-control" })
            @Html.ValidationMessageFor(m => m.HusbandCNP)
        </div>
        <div class="form-group">
            @Html.LabelFor(m => m.WifeName, "Nume sotie")
            @Html.TextBoxFor(m => m.WifeName, new { @class = "form-control" })
            @Html.ValidationMessageFor(m => m.WifeName)
        </div>
        <div class="form-group">
            @Html.LabelFor(m => m.WifeCNP, "CNP sotie")
            @Html.TextBoxFor(m => m.WifeCNP, new { @class = "form-control" })
            @Html.ValidationMessageFor(m => m.WifeCNP)
        </div>
        <div class="form-group">
            @Html.LabelFor(m => m.EmailAdress, "Adresa email")
            @Html.TextBoxFor(m => m.EmailAdress, new { @class = "form-control" })
            @Html.ValidationMessageFor(m => m.EmailAdress)
        </div>
        <div class="form-group">
            @Html.LabelFor(m => m.PhoneNumber, "Telefon")
            @Html.TextBoxFor(m => m.PhoneNumber, new { @class = "form-control" })
            @Html.ValidationMessageFor(m => m.PhoneNumber)
        </div>
        <div style="text-align:center">
            <button class="btn" style="width:400px;">Trimite</button>
        </div>


    }
    <br />
    <p id="blue">Atentie: Nu se pot rezerva două locaţii sau intervale orare pentru acelaşi cuplu. Daca doriti sa modificati locatia, sau data, va rugam sa anulati rezervarea efectuata.</p>
    <p id="black">Programarea on-line se poate utiliza numai in cazul casatoriilor incheiate intre cetateni romani. Pentru casatoria cu un cetatean strain, sau intre cetateni straini, va rugam sa va adresati ofiterului de stare civila de la ghiseu.</p>
    <p id="black">Casatoria se poate incheia dupa 11 zile de la data depunerii declaratiei de casatorie. (se socoteste atat ziua depunerii dosarului cat si ziua oficierii casatoriei).</p>
    <p id="blue">La depunerea declaratiei de casatorie este obligatorie prezenta ambilor soti, impreuna.</p>
    <p id="black">
        Pentru cazuri bine justificate, casatoria se poate incheia mai repede de 11 zile, ori dupa expirarea termenului legal, dar numai pana la expirarea termenului de valabilitate a certificatelor medicale ( de 14 zile de la data emiterii lor), cu aprobarea primarului.
        Casatoria civila se incheie in intervalul orar stabilit in acest scop, de catre Serviciul Stare Civila.
    </p>
    <p id="black">Prin continuarea procedurii de rezervare sunteti de acord cu prelucrarea datelor personale, in conformitate cu prevederile Legii nr.677/2001 pentru protectia persoanelor cu privire la prelucrarea datelor cu caracter personal si libera circulatie a acestor date.</pid="black">
    <p id="black">Declaratia de casatorie se face personal, de catre viitorii soti, in scris, la primaria locului de domiciliu sau de resedinta al unuia dintre soti.</p>
    <p id="black"> In cazul in care casatoria va fi cu un cetatean strain, va obligati sa solicitati, in timp util, informatii suplimentare despre actele necesare, dat fiind specificul fiecarei tari.</p>
    <p id="blue">Aveti obligatia de a inscrie corect si complet numele si prenumele sotilor, in caz contrar casatoria poate fi declarata nula prin neindeplinirea procedurii de publicitate (art. 283 din Cod Civil).</p>
    <p id="black">Declaratia de casatorie se face personal, de catre viitorii soti, in scris, la primaria in a carei raza de competenta teritoriala isi are domiciliul sau resedinta unul dintre viitorii soti.</p>
    <p id="black">Lipsa documentelor necesare si nerespectarea termenelor prevazute de lege, constituie atat conditie de fond, cat si impediment la incheierea casatoriei, care poate atrage dupa sine nulitatea casatoriei.</p>
    <br />
    <br />

</div>

@section Scripts {
    <script type="text/javascript">
        $(document).ready(function() {
            disableOrEnableHour();

            $("#Date").datepicker({
                dateFormat: "dd/MM/yy",
                changeMonth: true,
                changeYear: true,
                firstDay: 1,
                //beforeShowDay: $.datepicker.noWeekends,
                dateFormat: 'dd/mm/yy',
                language: "ro",
                dayNamesMin: ["Dum", "Lun", "Mar", "Mie", "Joi", "Vin", "Sam"],
                monthNamesShort: ["Ian", "Feb", "Mar", "Apr", "Mai", "Iun", "Iul", "Aug", "Sep", "Oct", "Nov", "Dec"]
            });

            $("#Date").change(function() {
                disableOrEnableHour();

                debugger;
                var actualDate = $("#Date").val();
                var bookedMarriages = @Html.Raw(Json.Encode(Model.BookedMarriages));
                $.each(bookedMarriages,
                    function(index, item) {
                        if (item.Key == actualDate) {
                            $('[name=Hour]').find('option:contains(' + item.Value.trim() + ')').prop('disabled', true);
                        }
                    });
            });
        });

        function disableOrEnableHour() {
            debugger;
            if (!$("#Date").val()) {
                $('#Hour option:eq(0)').attr('selected', 'selected');
                $("#Hour").prop("disabled", true);
            } else {
                $("#Hour").prop("disabled", false);
                $('[name=Hour]').find('option').prop('disabled', false);
            }
        }
    </script>
    <style>
        option:disabled {
            color: red;
            font-style:italic;
            font-size:15px;
            border:1px solid black;
        }
    </style>
}

Licenta/Views/Programari/_PageLinks.cshtml
<div>
    <p>@Html.ActionLink("Înregistrarea nașteri", "InregistrareNasteri", "Documente",null, new { @id = "white" }) </p>
    <p>@Html.ActionLink("Înregistrarea casătoriei", "InregistrareCasatorie", "Documente", null, new { @id = "white" }) </p>
    <p>@Html.ActionLink("Înregistrarea decesului", "InregistrareDeces", "Documente", null, new { @id = "white" }) </p>
    <p>@Html.ActionLink("Eliberarea / Preschimbarea certificatelor de stare civila", "EliberareCertificateStareCivila", "Documente", null, new { @id = "white" }) </p>
    <p>@Html.ActionLink("Divort pe cale administrativa", "Divort", "Documente", null, new { @id = "white" }) </p>
    <p>@Html.ActionLink("Livretul familiei", "LivretulFamiliei", "Documente", null, new { @id = "white" }) </p>
</div>