Licenta/Controllers/UserProfileController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web.Mvc;
using Licenta.Models;
using System.Text.Json;

namespace Licenta.Controllers
{
    public class UserProfileController : Controller
    {
        private UserActivity model;
        public UserProfileController()
        {
            var model=new UserActivity();
        }
        // GET: UserProfile
        public ActionResult Index()
        {
            var model=new UserActivity();
            var appSession = AppSession.Instance();
            //return View(new List<Audience>());
            using (var context = new DbLicentaEntities())
            {
                model.Audiences = context.Audience.Where(x => x.UserId == appSession.LoggedUser.Id).ToList();
                model.Reports= context.Report.Where(x => x.UserId == appSession.LoggedUser.Id).ToList();
                model.Marriages= context.Marriage.Where(x => x.UserId == appSession.LoggedUser.Id).ToList();
                
            }
            return View("Index",model);
        }

        public ActionResult CancelAudience(int audienceId)
        {
            using (var context = new DbLicentaEntities())
            {
                context.Audience.FirstOrDefault(x => x.IdAudienta == audienceId).isCanceled=true;
                 context.SaveChanges();
            }
            return Index();
        }
        public ActionResult CancelMarriage(int marriageId)
        {
            using (var context = new DbLicentaEntities())
            {
                context.Marriage.FirstOrDefault(x => x.Id== marriageId).IsCanceled=true;
                 context.SaveChanges();
            }
            return Index();
        }


        [HttpGet]
        [Route("GetData")]
        public ActionResult GetData()
        {

            List<Tuple<string, string>> result = new List<Tuple<string, string>>();
            DbLicentaEntities context = new DbLicentaEntities();
            var data = context.Marriage.ToList();
            foreach (var line in context.Marriage.GroupBy(info => info.Date)
                .Select(group => new
                {
                    Metric = group.Key,
                    Count = group.Count()
                })
                .OrderBy(x => x.Metric))
            {
                result.Add(new Tuple<string, string>(line.Metric, line.Count.ToString()));
            }

            return Json(JsonSerializer.Serialize(result),JsonRequestBehavior.AllowGet);
        }

        [HttpGet]
        [Route("GetDataForPie")]
        public ActionResult GetDataForPie()
        {
          
            DbLicentaEntities context = new DbLicentaEntities();
            int primar = context.Audience.Where(x => x.SolicitareLa == "primar").Count();
            int secretar = context.Audience.Where(x => x.SolicitareLa == "secretar").Count();
            int contabil = context.Audience.Where(x => x.SolicitareLa == "contabil").Count();
            int avocat = context.Audience.Where(x => x.SolicitareLa == "avocat").Count();
            Ratio obj = new Ratio();
            obj.primar = primar;
            obj.contabil = contabil;
            obj.secretar = secretar;
            obj.avocat = avocat;

            return Json(obj, JsonRequestBehavior.AllowGet);
        }
        public class Ratio
        {
            public int primar { get; set; }
            public int secretar { get; set; }
            public int contabil { get; set; }
            public int avocat { get; set; }
        }


        public ActionResult GetStatistics()
        {
            return View("AdminStatistic");
        }
     
        public ActionResult GetAudiencesChart()
        {
            return View("_AudiencesChart");
        }
      
        public ActionResult GetMarriagesChart()
        {
            return View("_MarriagesChart");
        }

        public ActionResult BackToStatistics()
        {
            return View("AdminStatistic");
        }
            
    }
};

Licenta/Views/UserProfile/AdminStatistic.cshtml
@{
    ViewBag.Title = "Statistici";
}


<h1 style="text-align:center">Statistici</h1>
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
<div class="row">
    <div class="col-md-6" style="text-align:center;font-size:25px">
        @Html.ActionLink("Grafic programări căsătorie", "GetMarriagesChart",null, new { @style = "color:white;" })
        <div style="text-align:center;font-size:300px;" >
            <i class="fa fa-line-chart" aria-hidden="true"></i>
        </div>
    </div>

    <div class="col-md-6" style="text-align:center;font-size:25px" >
        @Html.ActionLink("Grafic audiențe înregistrare", "GetAudiencesChart", null, new { @style = "color:white;" })
        <div style="text-align:center;font-size:300px;">
            <i class="fa fa-pie-chart" aria-hidden="true"></i>
        </div>
    </div>
</div>

Licenta/Views/UserProfile/Index.cshtml
@model Licenta.Models.UserActivity
<h1 style="text-align:center">Activitățile mele</h1>
<br />
<h2>Solicitări în audiență</h2>
<table id="reportTable" class="table table-bordered table-hover">
    <thead>
        <tr>
            <th>Id audienta</th>
            <th>Nume si prenume</th>
            <th>Telefon</th>
            <th>Audienta solicitata la</th>
            <th>Motivul</th>
            <th>Mentiuni</th>
        </tr>
    </thead>
    <tbody>
        @for (int i = 0; i < Model.Audiences.Count; i++)
        {
            if (!Model.Audiences[i].isCanceled)
            {
        <tr>
            <td @*hidden="true"*@>
                @Html.DisplayFor(x => x.Audiences[i].IdAudienta)
                @Html.HiddenFor(x => x.Audiences[i].IdAudienta)
            </td>
            <td>
                @Html.DisplayFor(x => x.Audiences[i].Nume)
                @Html.HiddenFor(x => x.Audiences[i].Nume)
            </td>
            <td>
                @Html.DisplayFor(x => x.Audiences[i].Telefon)
                @Html.HiddenFor(x => x.Audiences[i].Telefon)
            </td>
            <td>
                @Html.DisplayFor(x => x.Audiences[i].SolicitareLa)
                @Html.HiddenFor(x => x.Audiences[i].SolicitareLa)
            </td>
            <td>
                @Html.DisplayFor(x => x.Audiences[i].Motiv)
                @Html.HiddenFor(x => x.Audiences[i].Motiv)
            </td>
            <td>
                @Html.DisplayFor(x => x.Audiences[i].Mentiuni, new { @style = "color:royalblue" })
                @Html.HiddenFor(x => x.Audiences[i].Mentiuni)
            </td>
            <td>

                <input type="submit" class="show_alert" value="Anuleaza" show_alert="Esti sigur?" nextUrlAction="'@Url.Action("CancelAudience", "UserProfile",
                                                                               new {audienceId=@Model.Audiences[i].IdAudienta })'" />

            </td>

        </tr>
            }

        }
    </tbody>
</table>
<br />
<h2>Sesizări depuse</h2>
<table id="reportTable" class="table table-bordered table-hover">
    <thead>
        <tr>
            <td>Id sesizare</td>
            <th>Titlu</th>
            <th>Adresa</th>
            <th>Descriere</th>
            <th>Urgenta</th>
            <th>Rezolvata</th>
        </tr>
    </thead>
    <tbody>
        @for (int i = 0; i < Model.Reports.Count; i++)
        {
            <tr>
                <td>
                    @Html.DisplayFor(x => x.Reports[i].Id)
                    @Html.HiddenFor(x => x.Reports[i].Id)
                </td>
                <td>
                    @Html.DisplayFor(x => x.Reports[i].TitlulSesizarii)
                    @Html.HiddenFor(x => x.Reports[i].TitlulSesizarii)
                </td>
                <td>
                    @Html.DisplayFor(x => x.Reports[i].Adresa)
                    @Html.HiddenFor(x => x.Reports[i].Adresa)
                </td>
                <td>
                    @Html.DisplayFor(x => x.Reports[i].Descriere)
                    @Html.HiddenFor(x => x.Reports[i].Descriere)
                </td>
                <td>
                    @Html.DisplayFor(x => x.Reports[i].EsteUrgenta)
                    @Html.HiddenFor(x => x.Reports[i].EsteUrgenta)
                </td>

                <td>
                    @Html.CheckBoxFor(x => x.Reports[i].IsResolved, new { @disabled = "disabled" })
                    @Html.HiddenFor(x => x.Reports[i].IsResolved)
                </td>
            </tr>
        }
    </tbody>
</table>

<br />
<h2>Programări pentru căsătorie depuse</h2>
<table id="reportTable" class="table table-bordered table-hover">
    <thead>
        <tr>
            <td>Id casatorie</td>
            <th>Data</th>
            <th>Ora</th>
            <th>Sot</th>
            <th>CNP sot</th>
            <th>Sotie</th>
            <th>CNP sotie</th>
            <th>Email</th>
            <th>Telefon</th>
        </tr>
    </thead>
    <tbody>
        @for (int i = 0; i < Model.Marriages.Count; i++)
        {
            if (!Model.Marriages[i].IsCanceled)
            {
                <tr>
                    <td>
                        @Html.DisplayFor(x => x.Marriages[i].Id)
                        @Html.HiddenFor(x => x.Marriages[i].Id)
                    </td>
                    <td>
                        @Html.DisplayFor(x => x.Marriages[i].Date)
                        @Html.HiddenFor(x => x.Marriages[i].Date)
                    </td>
                    <td>
                        @Html.DisplayFor(x => x.Marriages[i].Hour)
                        @Html.HiddenFor(x => x.Marriages[i].Hour)
                    </td>
                    <td>
                        @Html.DisplayFor(x => x.Marriages[i].HusbandName)
                        @Html.HiddenFor(x => x.Marriages[i].HusbandName)
                    </td>

                    <td>
                        @Html.DisplayFor(x => x.Marriages[i].HusbandCNP)
                        @Html.HiddenFor(x => x.Marriages[i].HusbandCNP)
                    </td>
                    <td>
                        @Html.DisplayFor(x => x.Marriages[i].WifeName)
                        @Html.HiddenFor(x => x.Marriages[i].WifeName)
                    </td>
                    <td>
                        @Html.DisplayFor(x => x.Marriages[i].WifeCNP)
                        @Html.HiddenFor(x => x.Marriages[i].WifeCNP)
                    </td>
                    <td>
                        @Html.DisplayFor(x => x.Marriages[i].EmailAdress)
                        @Html.HiddenFor(x => x.Marriages[i].EmailAdress)
                    </td>
                    <td>
                        @Html.DisplayFor(x => x.Marriages[i].PhoneNumber)
                        @Html.HiddenFor(x => x.Marriages[i].PhoneNumber)
                    </td>
                    <td>

                        <input type="submit" value="Anuleaza" class="show_alert" show_alert="Esti sigur?" nextUrlAction="'@Url.Action("CancelMarriage", "UserProfile",
                                                                                        new {marriageId=@Model.Marriages[i].Id})'" />

                    </td>
                </tr>
            }

        }
    </tbody>
</table>


<style>
    .body-content {
        font-size: 20px;
        color: black;
    }
</style>


@section Scripts {
   
    <script type="text/javascript">
        jQuery(document).ready(function () {
            show_alert();
        });

        function show_alert() {
            debugger;
            jQuery('[show_alert]').click(function (e) {
                if (!confirm(jQuery(this).attr("show_alert"))) {
                    e.preventDefault();
                } else {
                    window.location.href = eval(jQuery(this).attr("nextUrlAction"));
                }
            });
        }
       
    </script>

}

Licenta/Views/UserProfile/_AudiencesChart.cshtml
<br />
<button class="btn">@Html.ActionLink("Statistici", "BackToStatistics", "UserProfile")</button>
<div class="row">
    <figure class="highcharts-figure">
        <div id="container1"></div>
        <p class="highcharts-description">

        </p>
    </figure>
</div>






@section Scripts{
    <script src="https://code.highcharts.com/highcharts.js"></script>
    <script src="https://code.highcharts.com/modules/exporting.js"></script>
    <script src="https://code.highcharts.com/modules/export-data.js"></script>
    <script src="https://code.highcharts.com/modules/accessibility.js"></script>
    <script>
        $(document).ready(function () {
            $.getJSON("/UserProfile/GetDataForPie",
                function (data) {
                    Highcharts.chart('container1', {
                        chart: {
                            plotBackgroundColor: null,
                            plotBorderWidth: null,
                            plotShadow: false,
                            type: 'pie'
                        },
                        title: {
                            text: 'Procentaj audiențe înregistrare'
                        },
                        tooltip: {
                            pointFormat: '{series.name}: <b>{point.percentage:.1f}%</b>'
                        },
                        accessibility: {
                            point: {
                                valueSuffix: '%'
                            }
                        },
                        plotOptions: {
                            pie: {
                                allowPointSelect: true,
                                cursor: 'pointer',
                                dataLabels: {
                                    enabled: true,
                                    format: '<b>{point.name}</b>: {point.percentage:.1f} %'
                                }
                            }
                        },
                        series: [{
                            name: 'Tip',
                            colorByPoint: true,
                            data: [{
                                name: 'Primar',
                                y: data.primar

                            }, {
                                name: 'Secretar',
                                y: data.secretar
                            }, {
                                name: 'Contabil',
                                y: data.contabil
                            }, {
                                name: 'Avocat',
                                y: data.avocat
                            }]
                        }]
                    });
                });
        });




    </script>

}
<style>
    .highcharts-figure,
    .highcharts-data-table table {
        min-width: 320px;
        max-width: 800px;
        margin: 1em auto;
    }

    .highcharts-data-table table {
        font-family: Verdana, sans-serif;
        border-collapse: collapse;
        border: 1px solid #EBEBEB;
        margin: 10px auto;
        text-align: center;
        width: 100%;
        max-width: 500px;
    }

    .highcharts-data-table caption {
        padding: 1em 0;
        font-size: 1.2em;
        color: #555;
    }

    .highcharts-data-table th {
        font-weight: 600;
        padding: 0.5em;
    }

    .highcharts-data-table td,
    .highcharts-data-table th,
    .highcharts-data-table caption {
        padding: 0.5em;
    }

    .highcharts-data-table thead tr,
    .highcharts-data-table tr:nth-child(even) {
        background: #f8f8f8;
    }

    .highcharts-data-table tr:hover {
        background: #f1f7ff;
    }


    input[type="number"] {
        min-width: 50px;
    }
</style>

Licenta/Views/UserProfile/_MarriagesChart.cshtml
<script src="https://code.highcharts.com/highcharts.js"></script>
<script src="https://code.highcharts.com/modules/exporting.js"></script>
<script src="https://code.highcharts.com/modules/export-data.js"></script>
<script src="https://code.highcharts.com/modules/accessibility.js"></script>
<br />
<button class="btn">@Html.ActionLink("Statistici", "BackToStatistics", "UserProfile")</button>
<div class="row">

    <figure class="highcharts-figure">
        <div id="container">



        </div>
        <br />
        <p class="highcharts-description">

            Graficul arată distribuția numărului de programări pentru căsătorie pe zile.
        </p>
    </figure>
</div>

@section Scripts {
    <script type="text/javascript">
        $(document).ready(function () {
            $.getJSON("/UserProfile/GetData",
                function (data) {
                    var counts = [];
                    var days = [];
                    (JSON.parse(data)).forEach(elem => {
                        counts.push(parseInt(elem.Item2));
                        days.push(elem.Item1);
                    });

                    Highcharts.chart('container',
                        {
                            chart: {
                                type: 'line'
                            },
                            title: {
                                text: 'Numărul de programări pentru casătorie/zile'
                            },
                            //subtitle: {
                            //    text: 'Source: WorldClimate.com'
                            //},
                            xAxis: {
                                categories: days
                            },
                            yAxis: {
                                title: {
                                    text: 'nr de zile'
                                }
                            },
                            plotOptions: {
                                line: {
                                    dataLabels: {
                                        enabled: true
                                    },
                                    enableMouseTracking: false
                                }
                            },
                            series: [
                                {
                                    name: 'Numărul de programări pentru căsătorie',
                                    data: counts
                                }
                            ]
                        });
                })
        })

    </script>
}