Licenta/Models/Login.cs
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;

namespace Licenta.Models
{
    public class Login
    {
        [DisplayName("Adresa de email") ]
        [Required(ErrorMessage ="Vă rugăm să introduceți adresa de email.")]
        public string EmailAddress { get; set; }
        [DisplayName("Parola")]
        [Required(ErrorMessage = "Vă rugăm să introduceți parola.")]
        public string Password { get; set; }

        public string LoginErrorMessage { get; set; }
        public string LogOutMessage { get; set; }

    }
}

Licenta/Controllers/CreateAccountController.cs
using System.Security.Cryptography;
using System.Text;
using System.Web.Mvc;
using Licenta.Models;

namespace Licenta.Controllers
{
    public class CreateAccountController : Controller
    {
        public CreateAccountController()
        {
        }
        // GET: CreateAccount
        public ActionResult Index()
        {
            return View(new CreateAccount());
        }

        public ActionResult Create(CreateAccount accountModel)
        {

            if (!ModelState.IsValid)
            {
                return View("Index", accountModel);
            }
            else
            {
                SHA256 sha256 = SHA256Managed.Create();
                UTF8Encoding objUtf8 = new UTF8Encoding();
                var hashValue = sha256.ComputeHash(objUtf8.GetBytes(accountModel.Password));
                using (var context = new DbLicentaEntities())
                {

                    context.User.Add(new User
                    {
                        Password = Encoding.Default.GetString(hashValue),
                        //Password=accountModel.Password,
                        EmailAddress = accountModel.EmailAddress,
                        IsAdmin = false
                    });
                    context.SaveChanges();
                }
                accountModel.AccountCreated = true;
                return View("Index", accountModel);
            }
           
        }
    }
}

Licenta/Controllers/LoginController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Security.Cryptography;
using System.Text;
using System.Web;
using System.Web.Mvc;
using Licenta.Models;
using Microsoft.Rest.ClientRuntime.Azure.Authentication.Utilities;

namespace Licenta.Controllers
{
    public class LoginController : Controller

    {
        
        // GET: Login
        public ActionResult Index()
        {
            ViewBag.Message = "Autentificare";

            return View();
        }

        public ActionResult Login(Login login)
        {
            if (!ModelState.IsValid)
            {
                return View("Index");
            }
            else
            {

            
            using(DbLicentaEntities db=new DbLicentaEntities())
            {
                //pt parola
                SHA256 sha256 = SHA256Managed.Create();
                UTF8Encoding objUtf8 = new UTF8Encoding();
                var hashValue = sha256.ComputeHash(objUtf8.GetBytes(login.Password));
                var hashedPassword = Encoding.Default.GetString(hashValue);


                var userDetails = db.User.Where(x => x.EmailAddress == login.EmailAddress
                    && x.Password==hashedPassword).FirstOrDefault();

                if (userDetails == null)
                {
                    
                    login.LoginErrorMessage = "Adresa de mail sau parola sunt gresite!";
                    return View("Index",login);
                }
                else
                {
                //    AppSession.IsUserLogged = true;
                //    AppSession.LoggedUser = userDetails;
                    AppSession.Login(userDetails);
                    return RedirectToAction("Index", "Home");
                }
            }
            }
        }

        public ActionResult LogOut()
        {
        
            AppSession.LogOut();
            return RedirectToAction("Index", "Home");
        }
    }
}

Licenta/Views/Login/Index.cshtml
@model Licenta.Models.Login
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">

<p id="title">Autentificare</p>


<p id="subtitle">Vă rugăm autentificați-vă
    </p>

<div class="row">
    <div class="col-lg-6 login">
        @using (Html.BeginForm("Login", "Login"))
        {
            @Html.ValidationSummary(true, "Pentru autentificare este nevoie sa completezi campurile de mai jos!")
            <div class="form-group">
                @Html.LabelFor(m => m.EmailAddress)
                @Html.TextBoxFor(m => m.EmailAddress, new { @class = "form-control" })
                @Html.ValidationMessageFor(m => m.EmailAddress)
            </div>
            <div class="form-group">
                @Html.LabelFor(m => m.Password)
                @Html.PasswordFor(m => m.Password, new { @class = "form-control" })
                @Html.ValidationMessageFor(m => m.Password)
            </div>
            <din>
                <label class="field-validation-error"> @Html.DisplayFor(m => m.LoginErrorMessage)</label>
            </din>
            <div style="text-align:center">
                <button class="btn"><i class="fa fa-sign-in" aria-hidden="true"></i> Intra in cont</button>
            </div>
        }
    </div>


    <div class="col-lg-6">
        <p id="newAccount">Daca nu ai un cont, te invităm să îți creezi unul.</p>
        <p id="newAccount">Te sfătuim să notezi datele pe care le folosești la crearea contului pentru a reduce riscurile de a nu-l mai putea folosi.</p>
        <br />
        <br />
        <br />
        <div style="text-align:center">
            <button class="btn"><i class="fa fa-plus-circle" aria-hidden="true"></i> @Html.ActionLink("Creare Cont", "Index", "CreateAccount")</button>
       </div>
     </div>
    </div>

<style>
    .row {
        margin-bottom: 30px;
    }

    .col-lg-6.login {
        font-size: 20px;
        border-right: 3px solid white;
        color: #bbbdbf;
    }

    #title {
        padding-top: 10px;
        text-align: center;
        color: black;
        border-bottom: 2px solid white;
        padding-bottom: 10px;
        font-size: 30px;
        font-family: Georgia, 'Times New Roman', Times, serif;
    }

    #subtitle {
      
        font-size: 25px;
        color: palevioletred;
        font-family: Georgia, 'Times New Roman', Times, serif;
    }

    #newAccount {
        font-size: 20px;
        font-family: Georgia, 'Times New Roman', Times, serif;
        color: black;
        margin-left:10px;
    }
</style>